/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface MentorshipApplication {
  'sessionType' : { 'free' : null } |
    { 'paid' : null },
  'name' : string,
  'email' : string,
  'goals' : string,
  'timestamp' : Time,
}
export interface PartnerInquiry {
  'partnerType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'organization' : string,
}
export interface Submission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VolunteerApplication {
  'interests' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllMentorshipApplications' : ActorMethod<
    [],
    Array<MentorshipApplication>
  >,
  'getAllPartnerInquiries' : ActorMethod<[], Array<PartnerInquiry>>,
  'getAllPrayerRequests' : ActorMethod<[], Array<Submission>>,
  'getAllVolunteerApplications' : ActorMethod<[], Array<VolunteerApplication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitMentorshipApplication' : ActorMethod<
    [string, string, { 'free' : null } | { 'paid' : null }, string],
    undefined
  >,
  'submitPartnerInquiry' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitPrayerRequest' : ActorMethod<[string, string, string], undefined>,
  'submitVolunteerApplication' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];