/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const MentorshipApplication = IDL.Record({
  'sessionType' : IDL.Variant({ 'free' : IDL.Null, 'paid' : IDL.Null }),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'goals' : IDL.Text,
  'timestamp' : Time,
});
export const PartnerInquiry = IDL.Record({
  'partnerType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'organization' : IDL.Text,
});
export const Submission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const VolunteerApplication = IDL.Record({
  'interests' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllMentorshipApplications' : IDL.Func(
      [],
      [IDL.Vec(MentorshipApplication)],
      ['query'],
    ),
  'getAllPartnerInquiries' : IDL.Func([], [IDL.Vec(PartnerInquiry)], ['query']),
  'getAllPrayerRequests' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getAllVolunteerApplications' : IDL.Func(
      [],
      [IDL.Vec(VolunteerApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitMentorshipApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'free' : IDL.Null, 'paid' : IDL.Null }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'submitPartnerInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitPrayerRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitVolunteerApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const MentorshipApplication = IDL.Record({
    'sessionType' : IDL.Variant({ 'free' : IDL.Null, 'paid' : IDL.Null }),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'goals' : IDL.Text,
    'timestamp' : Time,
  });
  const PartnerInquiry = IDL.Record({
    'partnerType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'organization' : IDL.Text,
  });
  const Submission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const VolunteerApplication = IDL.Record({
    'interests' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllMentorshipApplications' : IDL.Func(
        [],
        [IDL.Vec(MentorshipApplication)],
        ['query'],
      ),
    'getAllPartnerInquiries' : IDL.Func(
        [],
        [IDL.Vec(PartnerInquiry)],
        ['query'],
      ),
    'getAllPrayerRequests' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getAllVolunteerApplications' : IDL.Func(
        [],
        [IDL.Vec(VolunteerApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitMentorshipApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'free' : IDL.Null, 'paid' : IDL.Null }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'submitPartnerInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitPrayerRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitVolunteerApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };